### PR TITLE
Release v12.13.1 v14.19.2 and more

### PR DESCRIPTION
**Pull request by JalexChen**

### CODE REVIEW

**Review by felicianotech — APPROVED** [review]

**Comment by markwhitfeld** [comment]
@JalexChen It seems that this PR may have broken the `cimg/node:14.19` image.
This command now fails in 14.19.2 but used to work in 14.19.1: `sudo npm i -g claudia@5.1.1`
See details from SSH session:
image

**Comment by JalexChen** [comment]
Hi @markwhitfeld - are you sure you're spelling the package correctly? It looks like you're trying to install claidia@5.1.1. 

I am able to run and install `npm i -g claudia@5.1.1` with no problems

**Comment by markwhitfeld** [comment]
Thank you for the feedback. I think it might be a good option to provide some sort of message about the change due to the security concern so that it is visible in the CI build and therefore easier to resolve.
Potentially a fake `npm` and `node` that would be invoked under sudo which just simply outputs a message detailing the issue,

**Comment by JalexChen** [comment]
hi @markwhitfeld  - we'll definitely look into this and make a note to update the readme

**Pull request merged**
