### PR TITLE
Update `yarn` to `1.22.22`

### PR DESCRIPTION
**Pull request by DoodleBobBuffPants**
For our official CircleCI Docker Convenience Image support policy, please see [CircleCI docs](https://circleci.com/docs/convenience-images-support-policy).

This policy outlines the release, update, and deprecation policy for CircleCI Docker Convenience Images.

---

# Description
A brief description of the changes in this PR.

Updates `yarn` from `1.22.19` to `1.22.22`

# Reasons
Please provide reasoning for these changes and how this PR achieves them.

If applicable, include a link to the related GitHub issue that this PR will close.

Patch version update to pick up fixes for https://github.com/yarnpkg/yarn/issues/9005

# Checklist

Please check through the following before opening your PR. Thank you!

- [x] I have made changes to the `Dockerfile.template` file only
- [x] I have not made any manual changes to automatically generated files
- [x] My PR follows best practices as described in the [contributing guidelines](CONTRIBUTING)
- [x] (Optional, but recommended) My commits are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

### CODE REVIEW

**Comment by JalexChen** [comment]
Hi @DoodleBobBuffPants - we are going off the classic stable release per yarn docs. Additionally, it looks like the newest versions of yark have a couple of warnings against them on the [releases](https://github.com/yarnpkg/yarn/releases) page. I think placing this PR in the backlog until these are resolved so as to not break builds might be the best option for now. 

@ryanbourdais - any thoughts?

**Comment by schinery** [comment]
Maybe @DoodleBobBuffPants update this PR to 1.22.22 so it is good to go when someone gets around to looking at it again...

**Comment by schinery** [comment]
@JalexChen do you think this is good now to get merged so it's available in the next Node releases?

**Review by bjohnso5 — APPROVED** [review]

**Comment by vis97c** [comment]
This PR has introduced new issues on CI https://github.com/yarnpkg/yarn/issues/9015

**Pull request merged**
