### PR TITLE
Publish v14.21.2, v18.13.0, and v19.4.0. [release]

### PR DESCRIPTION
**Pull request by schinery**
Generated via `./shared/release.sh 14.21.2 18.13.0=lts 19.4.0=current`.

### CODE REVIEW

**Comment by vitalinfo** [comment]
any ETA when it could be merged?

**Comment by schinery** [comment]
Sorry to tag you directly @BytesGuy but is there a chance you might be able to give this PR a once over?

**Comment by asifrahmanvm** [comment]
It would be swell if we could merge this.

**Comment by BytesGuy** [comment]
Thanks for waiting folks, all image publishing was on hold due to the recent security incident. This should be good to go now

**Review by BytesGuy — APPROVED** [review]

**Pull request merged**
