### PR TITLE
Publish v12.13.1. [release]

### PR DESCRIPTION
**Pull request by felicianotech**
Older release that next-gen is missing. This is on request of a user.

### CODE REVIEW

**Review by KyleTryon — APPROVED** [review]

**Comment by nelzkiddom** [comment]
@felicianotech We are now seeing these issues in CircleCI builds:
```
Using SSH Config Dir '/home/circleci/.ssh'
git version 2.35.1
Cloning git repository
mkdir: cannot create directory ‘/root’: Permission denied
```

**Comment by felicianotech** [comment]
@nelzkiddom What is trying to create something in `/root`? To touch that directory, root permission is needed and thus a command needs to be prefixed with `sudo`. If you're trying to use something in that directory via a working_directory, cache, etc, you can't. Needs to be in `/home/circleci`.

**Comment by nelzkiddom** [comment]
The phase that is failing is the CircleCI-provided `- checkout` command.
The working directory is defined as `/root/project`, and this was working, and continues to work, in the `12.13.0` tagged image.

**Comment by nelzkiddom** [comment]
So, to be explicit...

With a job that looks like this:
```
  build:
    docker:
      - image: cimg/node:12.13 
    environment:
      NODE_ENV: test
    working_directory: /root/project
    steps:
      - checkout
```

It was working when the actual image resolved was `12.13.0`, but stopped working when you published `12.13.1`... E.g. the `12.13.1` image is not backwards-compatible.

**Comment by felicianotech** [comment]
The images aren't necessarily backwards compatible. The working directory is the problem. Can't be in root. Unless you explicitly need to set the working directory, I would recommend not setting it at all.

**Pull request merged**
